### ISSUE TITLE
UltraVNC is now on GitHub

### ISSUE THREAD

**Issue by Neustradamus** [copilot-com/UltraVNC#1]
There is now UltraVNC on GitHub:
- https://github.com/ultravnc/ultravnc

Offical dev:
- https://github.com/RudiDeVos

**Comment by Neustradamus** [comment]
@tghw: There is no change with the original source, can you delete this repository?

If there are changes, please do PRs:
- The official that you can fork is here: https://github.com/ultravnc/ultravnc

Thanks in advance.

**Comment by Neustradamus** [comment]
Guys, can you remove your forks, I see no change between this source?
@ewin66: https://github.com/ewin66/UltraVNC-1
@james-li: https://github.com/james-li/UltraVNC
@kylinxh: https://github.com/kylinxh/UltraVNC
@Mu-L: https://github.com/Mu-L/UltraVNC
@ssurui: https://github.com/ssurui/UltraVNC

The official that you can fork is here: https://github.com/ultravnc/ultravnc
@melaphor, @donaldcao, @lushuxian, @littleblank, @franklopeslr, @eds709394, @mystatistic, @wuxiyabear, @googlx

Do not hesitate to create PR if you have changes :)

**Comment by tghw** [comment]
@Neustradamus Thanks. I was waiting for the "official" version to go up. Consider this repo closed.
